# Homework 1 - Covariance Matrix

## Steps
* Get / Make a dataset to test √
* Be able to pull all values and put into their own variable √
* Write formula to find mean, sum, variance, and covariance √
* Calculate and store diffrerent covariances √
* Figure how to put in a matrix

In [139]:
import numpy as np

dataset = np.array([(1, 3, 1), (2, 2, 1), (3, 1, 2), (4, 1, 2)])

## Data

In [140]:
# Getting entire row of coordinates from matrix
X = dataset[:,0]
Y = dataset[:,1]
Z = dataset[:,2]


print("Dataset: \n", dataset)
print("\nColumns from matrix:")
print("X:", X)
print("Y:", Y)
print("Z:", Z)

Dataset: 
 [[1 3 1]
 [2 2 1]
 [3 1 2]
 [4 1 2]]

Columns from matrix:
X: [1 2 3 4]
Y: [3 2 1 1]
Z: [1 1 2 2]


## Formulas

In [186]:
# Variance
# sum of ((all values - mean)^2) /(total items - 1)


# My variance
def variance(data, name):
    print(f"Data For {name} Values".format(name))
    all_squared = []
    databar = np.mean(data)
    print("Mean :", databar)
    for i in data:
        datai = i
        difference = (datai - databar)
        squared = difference**2
        all_squared.append(squared)

#         print("\nData Point: ", datai)
#         print("Difference from the mean:", difference)
#         print("Squared: ", squared)

#     print("\nAll squared values: ",all_squared)
    nominator = np.sum(all_squared)
#     print("\nthe nominator: ", nominator)
    variance = nominator / (len(data)-1)
    print("The variance: ")
    return variance

# Covariance
def covariance(data1, data2, name1, name2):
    print(f"Covariance ({name1},{name2})".format(name1, name2))
    data1bar = np.mean(data1)
    data2bar = np.mean(data2)
    all_products = []
#     print("Mean of Data 1:", data1bar)
#     print("Mean of Data 2:", data2bar)
    for i in data1:
        data1i = i
        data2i = data2[i-1]
        difference1 = (data1i - data1bar)
        difference2 = (data2i - data2bar)
        product = difference1 * difference2
        all_products.append(product)

#         print(f"\nData Point: {data1i},{data2i}".format(data1i, data2i))
#         print(f"{name1} Difference from the mean:".format(), difference1)
#         print(f"{name2} Difference from the mean:".format(), difference2)
#         print("Products", product)
    
    
#     print("\nAll products: ", all_products)
    nominator = np.sum(all_products)
#     print("\nThe Nominator: ", nominator)
    covariance = nominator / (len(data1)-1)
    return covariance

    
# print("\nMy covariance: ", covariance(X, Y, "X", "Y"))
# cov = np.cov(X,Y)
# print("Numpy covariance: ", cov[0,1])


## Calculations

In [193]:
# VARIANCE 

#My Variance function
print(variance(X, "X"),'\n')
    # Built in Variance
    # print("\nNumpy Variance: ",np.var(X))
#My Variance function
print(variance(Y, "Y"),'\n')
    # Built in Variance
    # print("\nNumpy Variance: ",np.var(Y))
#My Variance function
print(variance(Z, "Z"),'\n\n')
    # Built in Variance
    # print("\nNumpy Variance: ",np.var(Z))


# COVARIANCE
print(covariance(X, X, "X", "X"),'\n')
print(covariance(X, Y, "X", "Y"),'\n')
print(covariance(X, Z, "X", "Z"),'\n')
print(covariance(Y, X, "Y", "X"),'\n')
print(covariance(Y, Y, "Y", "Y"),'\n')
print(covariance(Y, Z, "Y", "Z"),'\n')
print(covariance(Z, X, "Z", "X"),'\n')
print(covariance(Z, Y, "Z", "Y"),'\n')
print(covariance(Z, Z, "Z", "Z"),'\n')

Data For X Values
Mean : 2.5
The variance: 
1.6666666666666667 

Data For Y Values
Mean : 1.75
The variance: 
0.9166666666666666 

Data For Z Values
Mean : 1.5
The variance: 
0.3333333333333333 


Covariance (X,X)
1.6666666666666667 

Covariance (X,Y)
-1.1666666666666667 

Covariance (X,Z)
0.6666666666666666 

Covariance (Y,X)
0.9166666666666666 

Covariance (Y,Y)
-0.9166666666666666 

Covariance (Y,Z)
0.4166666666666667 

Covariance (Z,X)
0.3333333333333333 

Covariance (Z,Y)
-0.3333333333333333 

Covariance (Z,Z)
0.0 



# Application

In [214]:
import pandas as pd
import random

kepler = pd.read_csv("kepler.csv", delimiter =',')
# print(kepler.head(5))
# print(kepler[0],[0])
# print(kepler.iloc[:,10])
x = random.randint(2, 9564)
y = random.randint(2, 9564)
z = random.randint(2, 9564)
keplerX = kepler.iloc[:,x]
keplerY = kepler.iloc[:,y]
keplerZ = kepler.iloc[:,z]


# VARIANCE 
print(variance(keplerX, "keplerX"),'\n')
print(variance(keplerY, "keplerY"),'\n')
print(variance(keplerZ, "keplerZ"),'\n\n')

# COVARIANCE
print(covariance(keplerX, keplerX, "X", "X"),'\n')
print(covariance(keplerX, keplerY, "X", "Y"),'\n')
print(covariance(keplerX, keplerZ, "X", "Z"),'\n')
print(covariance(keplerY, keplerX, "Y", "X"),'\n')
print(covariance(keplerY, keplerY, "Y", "Y"),'\n')
print(covariance(keplerY, keplerZ, "Y", "Z"),'\n')
print(covariance(keplerZ, keplerX, "Z", "X"),'\n')
print(covariance(keplerZ, keplerY, "Z", "Y"),'\n')
print(covariance(keplerZ, keplerZ, "Z", "Z"),'\n')

IndexError: single positional indexer is out-of-bounds