# Linear Algebra

## Matrix Multiplication and Dot Product
Number of columns in 1st matrix HAS to equal the number of rows in 2nd matrix


In [48]:
import numpy as np

A = np.array([[1, 2], [0, 1], [2, 3]])
v = np.array([[2], [6]])
print(A)
print("\n")
print(v)
print("\n")
print(np.dot(A, v))
print("\n")
print(np.dot(v,A))


[[1 2]
 [0 1]
 [2 3]]


[[2]
 [6]]


[[14]
 [ 6]
 [22]]


Number of columns in 1st matrix HAS to equal the number of rows in 2nd matrix


ValueError: shapes (2,1) and (3,2) not aligned: 1 (dim 1) != 3 (dim 0)

In [8]:

A = np.array([[1, 2], [0, 1], [2, 3]])
B = np.array([[2, 5], [6, 7]])
print(A)
print(B)
print(np.dot(A, B))

[[1 2]
 [0 1]
 [2 3]]
[[2 5]
 [6 7]]
[[14 19]
 [ 6  7]
 [22 31]]


## Multiply by the "Identity Matrix" and then order of matrix multiplication does not matter (ex. AxB = BxA)

In [11]:
A = np.array([[1, 2], [0, 1]])
B = np.array([[1, 0], [0, 1]])
print(np.dot(A, B))
print(np.dot(B, A))

[[1 2]
 [0 1]]
[[1 2]
 [0 1]]


## Linear regression (Y-pred) in matrix-vector format

In [13]:

import numpy as np
import matplotlib.pyplot as plt

# Running Distance in Mile
x = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])

# Water Drinks in Litre
y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])
 


w1 = 0.25163494 
w0 = 0.79880123 
y_pred = [w1*i + w0 for i in x]
print(y_pred)

[1.629196532, 1.905994966, 2.1827934, 2.4872716774, 2.5426313642, 1.84761565992, 3.25953930826, 2.3544084290800003, 2.7087104245999996, 1.34409414498, 2.57081447748, 3.51419386754, 2.13573766622, 2.81112584518, 2.2215451807599997, 3.1314571237999997, 1.578869544]


## Another way of finding the y pred

Ypred = wX . (y predtion is the weights times the x matrix)

In [15]:
#create a vector of all 1s
v_ones = np.ones((1, len(x)))
print(v_ones)

# creat a matrix with one row of values of x and another row of all 1s
X = np.array([x, np.ones((1, len(x)))])
print(X)

# vector containing the weight
w = np.array([w1, w0])

#multiplying new array of Xs versus weights
#same as doing the y_pred formula above
np.dot(w, X)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[array([ 3.3  ,  4.4  ,  5.5  ,  6.71 ,  6.93 ,  4.168,  9.779,  6.182,
        7.59 ,  2.167,  7.042, 10.791,  5.313,  7.997,  5.654,  9.27 ,
        3.1  ])
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])]


array([[1.62919653, 1.90599497, 2.1827934 , 2.48727168, 2.54263136,
        1.84761566, 3.25953931, 2.35440843, 2.70871042, 1.34409414,
        2.57081448, 3.51419387, 2.13573767, 2.81112585, 2.22154518,
        3.13145712, 1.57886954]])

## Transpose

In [41]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A, '\n')

print(A.T, '\n')
#or
print(np.transpose(A))

print("A dimension: ",A.shape)
print("A.T dimension: ", A.T.shape)

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]]
A dimension:  (2, 3)
A.T dimension:  (3, 2)


## Norm of vector
The length of a vector is a nonnegative number that describes the extent of the vector in space, and is sometimes referred to as the vector’s magnitude or the norm.

In [45]:
from numpy import linalg as LA

v = np.array([[3], [4]])
print("Finsding the norm: ", LA.norm(v))
print("v", v)
print("v.T: ", v.T)
print("v times v.T: ", v * v.T)
print("v dot product v.T: ", np.dot(v, v.T))
print("Same as finding the norm: ", np.sqrt(np.dot(v, v.T)))
print("\n")
print("v dimension: ",v.shape)
print("v.T dimension: ", v.T.shape)

Finsding the norm:  5.0
v [[3]
 [4]]
v.T:  [[3 4]]
v times v.T:  [[ 9 12]
 [12 16]]
v dot product v.T:  [[ 9 12]
 [12 16]]
Same as finding the norm:  [[3.         3.46410162]
 [3.46410162 4.        ]]


v dimension:  (2, 1)
v.T dimension:  (1, 2)


## Activity: The distance between two vectors

![Image](https://github.com/Make-School-Courses/QL-1.1/raw/ae14402911c5c27954a66ff6074454a63ea54b46/Notebooks/Linear_Algebra/norm.png)

In [46]:

u = np.array([1, 1])
v = np.array([2, 2])
r = np.array([3, 8])

print(LA.norm(u - v))
print(LA.norm(u - r))
print(LA.norm(v - r))

1.4142135623730951
7.280109889280518
6.082762530298219
